inherit: true

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths:
    - src/*

build:
    nodes:
        php56:
            environment:
                php: 5.6

            tests:
                override:
                    -
                    command: composer test

        php71:
            environment:
                php: 7.1

            tests:
                override:
                    -
                    command: composer test
