inherit: true

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths:
    - src/*

build:
    environment:
        php: '5.6.16'
    tests:
        override:
            -
                php-scrutinizer-run --enable-security-analysis
                command: composer test
                coverage:
                    file: build/phpunit/clover.xml
                    format: php-clover
