inherit: true

filter:
    paths:
    - src/*

build:
    environment:
        php: '5.6.16'
    tests:
        override:
            -
                command: phpunit
                coverage:
                    format: php-clover
                    file: ./build/logs/clover.xml