sudo: required

dist: trusty

language: php

before_install:
  - sudo apt-get -y install git zip php5-cli php5-curl

before_script:
  - php -r "printf('PHP %s', phpversion());"
  - composer self-update
  - composer install --no-interaction

script:
  - phpunit

env:
  global:
    - secure: "ZQVeYv/QQHj7V+gNtR70e5CeNUM8WE3XOFUL2X/V3E7DHC7wzY/Dv74rXK/DxirKbnwhfXvlBWHmm+QrZr5Ayu9NU0yhMizZUi73btUZkb0o3eVkGUaAQlN3zfFz36boGvvsW+BMKjoB5h/D9IlpYdezmJkjB6lcctSGjkm27muJmFMBfhAaPwWHKuGv3Vw2C7LebYlOoCHujlRhh9zecvgMe1yjnpEGt0hM+DQxe6MEjt0SVfFCcPPhR6/sdbPH5DCjTtNqDyxs4qvSTPy1ogUY6Mr4mx/W7Ypb/kSO4oXpUnwyFvCS6MbSDUIFaPqj4P9xvLDsKgEmItmPKnjOb02ePDTsrpXdL15DsHs1VM/LJ0QHhITkDrmakeNPbtMIBM2/E6CvU66TVlRBgdeViF6OMhJZCm7iOw5N1sIjxHGfrukWdwmDReUIrRZ7/o3+IBN2f4bUBg8h400LQ5fQy8b5eKOKm1OfzWKi4ae1gJv0MAuUocmylmUPEqLOStjlSe/H0u5I01xfh887qunZDGAIPIuyOuMeZQiQLlYwbp8B4kErY3jE/89lrVAZeHJ2JOmN4DIUihPAC9/9uSm/6+6eMwXa38CXGdh7j3cU1FUIUIXpIMM2T9I6hfCo5eXxlZKGXqvJHmgpTxDYhsztP+ZdK6iu4bGFSavPd3LkC1M="
    - secure: "ovWiiGt9pB8OZKDuEHGGuK96lUGHzhsaje28G69tvLesJVDWPkM/DqePBkLGlMpJl05hSMPAjaJMysGi00OrdAgdTgHnFqq8neFMVRCdVadMUC+nol2AwFIb3yzGwzWLlmz4paGEVfARzYkDrltua59C6WlnU2dZAk7Pc8qV0HvRrTlu2/0M51zf+WdhB20YeU9jOOm9aCNpB0gTHhAOvt6XxCW9lYSvc5OYi52RlRITskJu/dUTVLv/c7nKQT5An7aViT6nqTimulw7wggdRE0h7HCZRj9aHgoxMgjgYdqNPlocSneTfsa+EKBNGg66yKX1iIis/yyR+uGDrV5vl4jOaWiq9fgeqjmJ8WiQRSGaGaNTisPRTo14RwGNtw29qKB5551qKLNwRkuh6TWGG00X584G1gaMNPoJqFiVf/SKpluAhC4bZjUxhm9no+0KK1hxYK/ekedREwi7CBa0WQ4N2vHqfgRegDa3K3JDDsX2Uyrs2t8B74+ClteIYS/n6V/JnHkiFkSe8H8ORlWOyIJHfyF9fSkd0YndWvp45HRbWqzVbZd+Eg+id4x8z8420kX8MoZuZf7iJul+xN2rXLmvkCCCRvxwL3i+34nUBkS64OcAxUK5wQdqeeAqSGKJvrVDhuuVrFaRPTr9slsJLO+3uV4dDb8Qspbx8rF+pTo="
