language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
 - composer self-update
 - composer install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit

env:
  global:
    - secure: "kDNyV0OniEOHRJ2l7+7OClXdPTKP6d86UE9rFvotShlHh1VceqoMDFA7WTPqjbcnUzpce4GiPdCbhXL3MzooBgslhim8Q1ZkELn7xmAvLqdMNrMRTwRtYsJxjcSKfk3Tq99y6v0M7H6k4r7O5keBhKp+Iut3k2D1WiyHIfwmqT+nNPiWqIL3FKnBTNOjZPPjWcTRAgrmCUEFvt5K5IH4hmagr8MkDWBEazb3yaTaBtAHre6Viq7VVyoKeDSV9XDETGJ5xaV1Ji+5rso+0Mq8IAoCZ+TRgYdGMDMWh8j1A3jk9giaGnreB/LzdK7I47C4FZkGTUwFag3D4sVqo5KOBkFdmStBU4ScIMPN+4vECFg3Ev6nh30GsTxZbKh5NUaI934snlU7944hq9mkXbLiEieJoKUQqEQCoJJSlCt1pv2A8YYY3jqQ2xpq5jEJtoTREHz7MVqArWMP7Y/hBsYcLSh8sTtTsnHP9KkA5Dhwd6fx/nUPf0dzY6uEF18j70gu9bxo8SzAKIIcw9Sxp6R6hWZeRH7EFpfg9TwJ02Xc1l1HpQ+nm3fNtyTg5iitEeiGU2ot5rmPVw9237SP7/RQuqfw+qsopwCS63gRDik1Fp1+AGiNYegNwv4CSeCm+yTPKAbRMjwQl3PJzVodcLPnNC4UXu0oA5e6ZAbR3B8oXbc="
    - secure: "chzY5JdkKdxSlK8YZcLnDf+0a33WUhPv9mcsapSmlXqqFNx8MRqZ+P+4RbZiz33lw3kpzhsYzH5rVQs4NYuktlO/ud1nGn7z+ELwo8/p26dAlqFlcR+hR8y+i//y8/oBEaqvwJRg0yAPArCDbxKJfVBk6HewjB2bldin2AKyloRag2JxwWIzDpG4hBtIY82rtcj5gyQEhA9hUxAtleVcaB4VDbdStetqAkZxIg6F5nPhLC3K8PN/BD74wplUzdiUpXw8xJvkTGOXfIG2rpXmvyoZ8BIgW6RR6gDEx2LTxe/DoF/coCPIE0OW3zbIj51zhpp9vQCb57O7nsEcW/dz8DvVNV2Y5Efb/ip6RatH3ZfvDo5HPaP8TLnDkp/mN17IgY9fVRkIjzi0js4J4W7r5NFmqhkI24q6goB/HHdQu/RFxFykzSj+uUQ0xL8/zRGrJcl/C/URwjmWIYRx+6tEpMIzlB1uWbZp44XLij7QsNTT8+ulegSW2kNeG9Hs+IkDISg/k0+FT3qKKusFem58L9/bx7lYzwMzf93bCDyB1wArSH45mVPuD7pmfFl614vcrqWDzbLEMSvQXqqIqhPaIQuXFUgmSjsGjmNcioXwke9U5ZrqX08QsBVWK3WX26fvxweNf5fT5lTC7+41pZyrtDxG1CFRAfe4SmT8w0mg3/U="
